version: "3.4"

services:
  cafihsa-web:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: cafihsa-web
    ports:
      - "3000:3000"

  cafihsa-api:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: cafihsa-api
    ports:
      - "5038:5038"
      - "7030:7030"
    depends_on:
      - cafihsa-db

  cafihsa-db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    container_name: cafihsa-db
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"
